### ISSUE TITLE
start/stop/restart feature request

### ISSUE THREAD

**Issue by Stoner19** [filipealmeida/liskak#5]
Ideally it would be nice to be able to start and stop `./liskak` without having to `kill` the process. Is it at all possible to roll some kind of function into it that makes it easier for the user to stop the process? something along the line of `./liskak stop` or maybe have the process output the running scripts (similar to that of a running bash script) so that users can terminate by using `ctrl+c`, just run it with screen, forever, or something similar.

**Comment by filipealmeida** [comment]
Hi, first and foremost, please notice that liskak is a command-line tool, no API, no exposed ports, self contained.
Since is a normal process, the process management is left to the sysadmin to handle as he prefers through the normal channels of OS signal processing.
On windows, such killing process could be a combination of tasklist, wmic, get-process, find-str and taskkill.
On linux, the number of options are even grater: ps, grep, pidof, pkill and kill are some of the popular scripts.

Having said that, we've got you covered, you can use the scripts present in this repo contributed by Isabella: monitorTest.sh, monitorNode.sh and monitorMain.sh.
If you use these, the liskak node process is terminated before executing again :)
Please refer to the lisk forums and chatrooms for guidance, there are many flavours to achieve what you're pursuing and a lot of creativity you should explore. 

If you have trouble with these scripts, please feel free to post an issue.
Go lisk, go.
